use std::env;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    emit_rerun_for_dir(Path::new("src"));
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=Cargo.lock");
    println!("cargo:rerun-if-env-changed=BR2_SUMMIT_BUILD_VERSION");

    let build_version = env::var("BR2_SUMMIT_BUILD_VERSION")
        .or_else(|_| env::var("CARGO_PKG_VERSION"))
        .unwrap_or_else(|_| "0.0.0.0".to_string());
    println!("cargo:rustc-env=SUMMIT_RCM_BUILD_VERSION={build_version}");

    if let Err(error) = generate_builtin_plugin_registry() {
        panic!("failed to generate builtin plugin registry: {error}");
    }
}

fn emit_rerun_for_dir(dir: &Path) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                emit_rerun_for_dir(&path);
            } else if path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
                println!("cargo:rerun-if-changed={}", path.display());
            }
        }
    }
}

fn generate_builtin_plugin_registry() -> Result<(), Box<dyn Error>> {
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let output_path = out_dir.join("builtin_plugins.rs");
    let plugins_dir = Path::new("src/plugins");
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);

    let mut plugins = fs::read_dir(&plugins_dir)?
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter_map(|path| {
            if path.is_file() && path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
                let module_name = path
                    .file_stem()
                    .and_then(|stem| stem.to_str())
                    .map(str::to_owned);
                return module_name.map(|module_name| (module_name, path));
            }

            if path.is_dir() && path.join("mod.rs").is_file() {
                let module_name = path
                    .file_name()
                    .and_then(|name| name.to_str())
                    .map(str::to_owned);
                return module_name.map(|module_name| (module_name, path.join("mod.rs")));
            }

            None
        })
        .filter(|(module_name, _)| module_name != "mod")
        .filter(|(module_name, _)| module_name != "systemd_state")
        .collect::<Vec<_>>();
    plugins.sort_by(|left, right| left.0.cmp(&right.0));
    plugins.dedup_by(|left, right| left.0 == right.0);

    let mut content = String::from("// @generated by build.rs\n");
    for (module_name, source_path) in &plugins {
        let feature_name = module_name.replace('_', "-");
        let source_path = manifest_dir.join(source_path);
        let source_path = source_path.display();
        content.push_str(&format!(
            "#[cfg(feature = \"{feature_name}\")]\n#[path = \"{source_path}\"]\npub mod {module_name};\n"
        ));
    }

    write_if_changed(&output_path, &content)?;
    Ok(())
}

fn write_if_changed(path: &Path, content: &str) -> Result<(), Box<dyn Error>> {
    match fs::read_to_string(path) {
        Ok(existing) if existing == content => return Ok(()),
        Ok(_) | Err(_) => {}
    }

    fs::write(path, content)?;
    Ok(())
}