use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=src/plugins");
    println!("cargo:rerun-if-env-changed=BR2_SUMMIT_BUILD_VERSION");

    let build_version = env::var("BR2_SUMMIT_BUILD_VERSION")
        .or_else(|_| env::var("CARGO_PKG_VERSION"))
        .unwrap_or_else(|_| "0.0.0.0".to_string());
    println!("cargo:rustc-env=SUMMIT_RCM_BUILD_VERSION={build_version}");

    let plugins_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("src/plugins");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // The generated list is `include!`d from `src/plugins/mod.rs`, so a bare
    // `pub mod <name>;` resolves relative to OUT_DIR. Use an absolute `#[path]`
    // to point each module at its real source. Feature gating lives in each
    // plugin's own `mod.rs`.
    let mut content = String::from("// @generated by build.rs\n");
    let pattern = format!("{}/{}", glob::Pattern::escape(&plugins_dir.to_string_lossy()), "*/mod.rs");
    for entry in glob::glob(&pattern).unwrap() {
        match entry {
            Ok(src) => {
                let name = src.parent().unwrap().file_name().unwrap().to_string_lossy();
                content.push_str(&format!("#[path = \"{}\"]\npub mod {name};\n", src.display()));
            }
            Err(_) => {}
        }
    }

    let output = out_dir.join("builtin_plugins.rs");
    if fs::read_to_string(&output).unwrap_or_default() != content {
        fs::write(&output, &content).unwrap();
    }
}

