//
// SPDX-License-Identifier: LicenseRef-Ezurio-Clause
// Copyright (C) 2026 Ezurio LLC.
//
//! Force-link enabled plugin crates into an integration-test binary so their
//! `inventory::submit!` registrations (AT commands, routes, OpenAPI) are
//! present. Generated by build.rs from the manifest dependency list; shared by
//! the binaries and any test that exercises the cross-plugin registry.

include!(concat!(env!("OUT_DIR"), "/plugin_links.rs"));
