
//
// SPDX-License-Identifier: LicenseRef-Ezurio-Clause
// Copyright (C) 2026 Ezurio LLC.
//

//! Shared application-wide D-Bus helpers.

use std::os::fd::AsRawFd;
use anyhow::Result;
use log::warn;
use serde_json::{json, Value as JsonValue};
use serde::{de::DeserializeOwned, Serialize};
use std::borrow::Cow;
use std::collections::HashMap;
use std::sync::{Arc, LazyLock};
use tokio::sync::RwLock;
use std::time::Duration;
use zbus::{
    connection::Builder,
    message::Type as MessageType,
    zvariant::{OwnedValue, Type, Value},
    Connection, MatchRule, Message, MessageStream,
};

pub const DBUS_PROP_IFACE: &str = "org.freedesktop.DBus.Properties";
pub const TEST_SYSTEM_BUS_ADDRESS_ENV: &str = "SUMMIT_RCM_TEST_SYSTEM_BUS_ADDRESS";
pub const DBUS_METHOD_TIMEOUT_MS_ENV: &str = "SUMMIT_RCM_DBUS_METHOD_TIMEOUT_MS";

#[derive(Debug)]
pub enum DbusCallError {
    Timeout {
        interface: Option<String>,
        method: String,
        timeout_ms: String,
    },
    Method(zbus::Error),
}

impl std::fmt::Display for DbusCallError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Timeout {
                interface,
                method,
                timeout_ms,
            } => write!(
                f,
                "D-Bus call {}.{} timed out after {} ms",
                interface.as_deref().unwrap_or("<none>"),
                method,
                timeout_ms
            ),
            Self::Method(error) => write!(f, "{error}"),
        }
    }
}

impl std::error::Error for DbusCallError {}

impl From<zbus::Error> for DbusCallError {
    fn from(error: zbus::Error) -> Self {
        Self::Method(error)
    }
}

/// Returns true when an anyhow error chain contains a D-Bus timeout error generated by this module.
pub fn is_timeout_error(error: &anyhow::Error) -> bool {
    error.chain().any(|cause| {
        matches!(
            cause.downcast_ref::<DbusCallError>(),
            Some(DbusCallError::Timeout { .. })
        )
    })
}

type ConnectionCacheKey = (Cow<'static, str>, Option<u64>);

static SYSTEM_BUS_CONNECTIONS: LazyLock<RwLock<HashMap<ConnectionCacheKey, Arc<Connection>>>> =
    LazyLock::new(|| RwLock::new(HashMap::new()));

pub trait ConnectionRef {
    fn connection(&self) -> &Connection;
}

impl ConnectionRef for Connection {
    fn connection(&self) -> &Connection {
        self
    }
}

impl ConnectionRef for &Connection {
    fn connection(&self) -> &Connection {
        self
    }
}

impl ConnectionRef for Arc<Connection> {
    fn connection(&self) -> &Connection {
        self.as_ref()
    }
}

impl ConnectionRef for &Arc<Connection> {
    fn connection(&self) -> &Connection {
        self.as_ref()
    }
}

fn timeout_cache_key(timeout: Option<Duration>) -> Option<u64> {
    timeout.map(|value| value.as_millis().min(u64::MAX as u128) as u64)
}

fn current_system_bus_key() -> Cow<'static, str> {
    std::env::var(TEST_SYSTEM_BUS_ADDRESS_ENV)
        .ok()
        .filter(|value| !value.trim().is_empty())
        .map(Cow::Owned)
        .unwrap_or(Cow::Borrowed("__system__"))
}

static DBUS_METHOD_TIMEOUT: LazyLock<Duration> = LazyLock::new(|| {
    let default_timeout_ms: u64 = 2_000;
    match std::env::var(DBUS_METHOD_TIMEOUT_MS_ENV) {
        Ok(value) => {
            let trimmed = value.trim();
            match trimmed.parse::<u64>() {
                Ok(timeout_ms) if timeout_ms > 0 => Duration::from_millis(timeout_ms),
                _ => {
                    warn!(
                        "Invalid {}='{}'; using default {} ms",
                        DBUS_METHOD_TIMEOUT_MS_ENV,
                        trimmed,
                        default_timeout_ms
                    );
                    Duration::from_millis(default_timeout_ms)
                }
            }
        }
        Err(_) => Duration::from_millis(default_timeout_ms),
    }
});

fn dbus_method_timeout() -> Duration {
    *DBUS_METHOD_TIMEOUT
}

async fn connect_system_bus(key: &str, timeout: Option<Duration>) -> Result<Connection> {
    let builder = if key == "__system__" {
        Builder::system()?
    } else {
        Builder::address(key)?
    };

    let builder = match timeout {
        Some(timeout) => builder.method_timeout(timeout),
        None => builder,
    };

    builder.build().await.map_err(Into::into)
}

async fn evict_cached_connection(conn: &Connection) {
    SYSTEM_BUS_CONNECTIONS
        .write()
        .await
        .retain(|_, cached_conn| !std::ptr::eq(cached_conn.as_ref(), conn));
}

/// Return the shared system bus connection for the application.
pub async fn system_bus() -> Result<Arc<Connection>> {
    system_bus_with_timeout(Some(dbus_method_timeout())).await
}

/// Return a shared system bus connection for the application with a specific zbus method timeout.
pub async fn system_bus_with_timeout(timeout: Option<Duration>) -> Result<Arc<Connection>> {
    let cache_key = (current_system_bus_key(), timeout_cache_key(timeout));

    if let Some(connection) = SYSTEM_BUS_CONNECTIONS
        .read()
        .await
        .get(&cache_key)
        .cloned()
    {
        return Ok(connection);
    }

    let connection = Arc::new(connect_system_bus(&cache_key.0, timeout).await?);
    let mut connections = SYSTEM_BUS_CONNECTIONS.write().await;
    match connections.entry(cache_key) {
        std::collections::hash_map::Entry::Occupied(entry) => Ok(entry.get().clone()),
        std::collections::hash_map::Entry::Vacant(entry) => {
            entry.insert(connection.clone());
            Ok(connection)
        }
    }
}

pub async fn call_method_deserialize<T, B>(
    conn: impl ConnectionRef,
    destination: Option<&str>,
    path: &str,
    interface: Option<&str>,
    method: &str,
    body: &B,
) -> Result<T>
where
    T: DeserializeOwned + Type,
    B: Serialize + Type,
{
    let conn = conn.connection();
    let reply = call_method_typed(
        conn,
        destination,
        path,
        interface,
        method,
        body,
        Some(dbus_method_timeout()),
    )
    .await?;
    reply.body().deserialize().map_err(Into::into)
}

pub async fn call_method_deserialize_with_timeout<T, B>(
    conn: impl ConnectionRef,
    destination: Option<&str>,
    path: &str,
    interface: Option<&str>,
    method: &str,
    body: &B,
    timeout: Option<Duration>,
) -> Result<T>
where
    T: DeserializeOwned + Type,
    B: Serialize + Type,
{
    let conn = conn.connection();
    let reply = call_method_typed(conn, destination, path, interface, method, body, timeout).await?;
    reply.body().deserialize().map_err(Into::into)
}

pub async fn call_method<B>(
    conn: impl ConnectionRef,
    destination: Option<&str>,
    path: &str,
    interface: Option<&str>,
    method: &str,
    body: &B,
    timeout: Option<Duration>,
) -> Result<Message>
where
    B: Serialize + Type,
{
    call_method_typed(conn, destination, path, interface, method, body, timeout)
        .await
        .map_err(Into::into)
}

pub async fn call_method_typed<B>(
    conn: impl ConnectionRef,
    destination: Option<&str>,
    path: &str,
    interface: Option<&str>,
    method: &str,
    body: &B,
    timeout: Option<Duration>,
) -> std::result::Result<Message, DbusCallError>
where
    B: Serialize + Type,
{
    let conn = conn.connection();
    if let Some(requested_timeout) = timeout
        && conn.method_timeout() != Some(requested_timeout) {
            warn!(
                "D-Bus call {}.{} requested {} ms but connection timeout is {:?}; using connection timeout",
                interface.unwrap_or("<none>"),
                method,
                requested_timeout.as_millis(),
                conn.method_timeout().map(|value| value.as_millis())
            );
        }

    match conn
        .call_method(destination, path, interface, method, body)
        .await
    {
        Ok(reply) => Ok(reply),
        Err(error) => {
            let timed_out = matches!(
                &error,
                zbus::Error::InputOutput(io_error)
                    if io_error.kind() == std::io::ErrorKind::TimedOut
            );

            if timed_out {
                evict_cached_connection(conn).await;
                if let Err(close_error) = conn.clone().close().await {
                    warn!("Failed to close D-Bus connection after timeout: {close_error}");
                }

                let timeout_ms = conn
                    .method_timeout()
                    .or(timeout)
                    .map(|value| value.as_millis().to_string())
                    .unwrap_or_else(|| "unknown".to_string());

                return Err(DbusCallError::Timeout {
                    interface: interface.map(str::to_owned),
                    method: method.to_string(),
                    timeout_ms,
                });
            }

            Err(DbusCallError::Method(error))
        }
    }
}

pub async fn get_property<T>(
    conn: impl ConnectionRef,
    destination: &str,
    path: &str,
    interface: &str,
    property_name: &str,
) -> Result<T>
where
    T: TryFrom<OwnedValue>,
    <T as TryFrom<OwnedValue>>::Error: Into<anyhow::Error>,
{
    let conn = conn.connection();
    get_property_with_timeout(conn, destination, path, interface, property_name, Some(dbus_method_timeout())).await
}

pub async fn get_property_with_timeout<T>(
    conn: impl ConnectionRef,
    destination: &str,
    path: &str,
    interface: &str,
    property_name: &str,
    timeout: Option<Duration>,
) -> Result<T>
where
    T: TryFrom<OwnedValue>,
    <T as TryFrom<OwnedValue>>::Error: Into<anyhow::Error>,
{
    let conn = conn.connection();
    let value: OwnedValue = call_method_deserialize_with_timeout(
        conn,
        Some(destination),
        path,
        Some(DBUS_PROP_IFACE),
        "Get",
        &(interface, property_name),
        timeout,
    )
    .await?;
    value.try_into().map_err(Into::into)
}

pub async fn set_property(
    conn: impl ConnectionRef,
    destination: &str,
    path: &str,
    interface: &str,
    property_name: &str,
    value: Value<'static>,
) -> Result<()> {
    let conn = conn.connection();
    set_property_with_timeout(
        conn,
        destination,
        path,
        interface,
        property_name,
        value,
        Some(dbus_method_timeout()),
    )
    .await
}

pub async fn set_property_with_timeout(
    conn: impl ConnectionRef,
    destination: &str,
    path: &str,
    interface: &str,
    property_name: &str,
    value: Value<'static>,
    timeout: Option<Duration>,
) -> Result<()> {
    let conn = conn.connection();
    call_method(
        conn,
        Some(destination),
        path,
        Some(DBUS_PROP_IFACE),
        "Set",
        &(interface, property_name, value),
        timeout,
    )
    .await?;
    Ok(())
}

pub async fn subscribe_to_signal(
    sender: &str,
    interface: &str,
    member: &str,
    max_queued: usize,
) -> Result<MessageStream> {
    let connection = system_bus().await?;
    let rule = MatchRule::builder()
        .msg_type(MessageType::Signal)
        .sender(sender)
        .and_then(|builder| builder.interface(interface))
        .and_then(|builder| builder.member(member))
        .map(|builder| builder.build())
        .map_err(|_| anyhow::anyhow!("failed to build D-Bus signal match rule"))?;
    MessageStream::for_match_rule(rule, connection.as_ref(), Some(max_queued))
        .await
        .map_err(|error| anyhow::anyhow!("failed to subscribe to D-Bus signal stream: {error}"))
}

pub fn clone_owned_value(value: &OwnedValue) -> Result<OwnedValue> {
    value.try_clone().map_err(Into::into)
}

pub fn try_from_owned_value<T>(value: &OwnedValue) -> Option<T>
where
    T: TryFrom<OwnedValue>,
{
    clone_owned_value(value)
        .ok()
        .and_then(|value| T::try_from(value).ok())
}

pub fn property<T>(properties: &HashMap<String, OwnedValue>, key: &str) -> Option<T>
where
    T: TryFrom<OwnedValue>,
{
    properties.get(key).and_then(try_from_owned_value::<T>)
}

#[cfg(feature = "bluetooth")]
pub fn property_or_default<T>(properties: &HashMap<String, OwnedValue>, key: &str) -> T
where
    T: TryFrom<OwnedValue> + Default,
{
    property(properties, key).unwrap_or_default()
}

#[cfg(feature = "bluetooth")]
pub fn property_bytes_hex(properties: &HashMap<String, OwnedValue>, key: &str) -> Option<String> {
    property::<Vec<u8>>(properties, key).map(hex::encode)
}

fn value_to_json(value: &Value<'_>) -> JsonValue {
    match value {
        Value::U8(v) => json!(v),
        Value::Bool(v) => json!(v),
        Value::I16(v) => json!(v),
        Value::U16(v) => json!(v),
        Value::I32(v) => json!(v),
        Value::U32(v) => json!(v),
        Value::I64(v) => json!(v),
        Value::U64(v) => json!(v),
        Value::F64(v) => json!(v),
        Value::Str(v) => json!(v.to_string()),
        Value::Signature(v) => json!(v.to_string()),
        Value::ObjectPath(v) => json!(v.to_string()),
        Value::Value(v) => value_to_json(v.as_ref()),
        Value::Array(v) => {
            let values = v.inner();
            let mut json_values = Vec::with_capacity(values.len());
            for value in values {
                json_values.push(value_to_json(value));
            }
            JsonValue::Array(json_values)
        }
        Value::Dict(v) => {
            let iter = v.iter();
            let mut entries = serde_json::Map::with_capacity(iter.size_hint().0);
            for (key, value) in iter {
                let key = match value_to_json(key) {
                    JsonValue::String(key) => key,
                    other => other.to_string(),
                };
                entries.insert(key, value_to_json(value));
            }
            JsonValue::Object(entries)
        }
        Value::Structure(v) => {
            let fields = v.fields();
            let mut json_fields = Vec::with_capacity(fields.len());
            for field in fields {
                json_fields.push(value_to_json(field));
            }
            JsonValue::Array(json_fields)
        }
        #[cfg(unix)]
        Value::Fd(v) => json!(v.as_raw_fd()),
    }
}

pub fn owned_value_to_json(value: &OwnedValue) -> JsonValue {
    value_to_json(value)
}