//
// SPDX-License-Identifier: LicenseRef-Ezurio-Clause
// Copyright (C) 2026 Ezurio LLC.
//
// @generated by tools/generate_nm_connection_profile.py
// Source: /devel/cp_linux/summit-radio-devel-external/externals/lrd-network-manager

use serde::{Deserialize, Deserializer, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;

fn deserialize_optional_string_vec<'de, D>(deserializer: D) -> Result<Option<Vec<String>>, D::Error>
where
    D: Deserializer<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum StringVecOrString {
        Many(Vec<String>),
        One(String),
    }

    Ok(match Option::<StringVecOrString>::deserialize(deserializer)? {
        None => None,
        Some(StringVecOrString::Many(values)) => Some(values),
        Some(StringVecOrString::One(value)) => Some(vec![value]),
    })
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "api-docs", derive(utoipa::ToSchema))]
pub struct ConnectionSettingsConnection {
    #[serde(rename = "auth-retries")]
    pub auth_retries: Option<i64>,
    /// Whether or not the connection should be automatically connected by NetworkManager when the
    /// resources for the connection are available. TRUE to automatically activate the connection, FALSE
    /// to require manual intervention to activate the connection. Autoconnect happens when the
    /// circumstances are suitable. That means for example that the device is currently managed and not
    /// active. Autoconnect thus never replaces or competes with an already active profile. Note that
    /// autoconnect is not implemented for VPN profiles. See "secondaries" as an alternative to
    /// automatically connect VPN profiles. If multiple profiles are ready to autoconnect on the same
    /// device, the one with the better "connection.autoconnect-priority" is chosen. If the priorities
    /// are equal, then the most recently connected profile is activated. If the profiles were not
    /// connected earlier or their "connection.timestamp" is identical, the choice is undefined.
    /// Depending on "connection.multi-connect", a profile can (auto)connect only once at a time or
    /// multiple times.
    pub autoconnect: Option<bool>,
    #[serde(rename = "autoconnect-ports")]
    pub autoconnect_ports: Option<i64>,
    #[serde(rename = "autoconnect-priority")]
    pub autoconnect_priority: Option<i64>,
    #[serde(rename = "autoconnect-retries")]
    pub autoconnect_retries: Option<i64>,
    /// Deprecated by NetworkManager.
    #[serde(rename = "autoconnect-slaves")]
    pub autoconnect_slaves: Option<i64>,
    /// Interface name of the controller device or UUID of the controller connection.
    pub controller: Option<String>,
    #[serde(rename = "dns-over-tls")]
    pub dns_over_tls: Option<i64>,
    /// Whether DNSSEC (dnssec) is enabled for the connection. The permitted values are: "yes" (2) use
    /// DNSSEC and disable fallback, "allow-downgrade" (1) use DNSSEC but allow fallback if the server
    /// does not support it, "no" (0) don't ever use DNSSEC. The effect of "default" (-1) depends on the
    /// dns plugin used. Systemd-resolved uses its global setting in this case. This feature requires a
    /// plugin which supports DNSSEC. Otherwise, the setting has no effect. One such plugin is systemd-
    /// resolved.
    pub dnssec: Option<i64>,
    #[serde(rename = "down-on-poweroff")]
    pub down_on_poweroff: Option<i64>,
    #[serde(rename = "gateway-ping-timeout")]
    pub gateway_ping_timeout: Option<i64>,
    /// A human readable unique identifier for the connection, like "Work Wi-Fi" or "T-Mobile 3G".
    pub id: Option<String>,
    #[serde(rename = "interface-name")]
    pub interface_name: Option<String>,
    #[serde(rename = "ip-ping-addresses")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub ip_ping_addresses: Option<Vec<String>>,
    #[serde(rename = "ip-ping-addresses-require-all")]
    pub ip_ping_addresses_require_all: Option<i64>,
    #[serde(rename = "ip-ping-timeout")]
    pub ip_ping_timeout: Option<i64>,
    /// Whether LLDP is enabled for the connection.
    pub lldp: Option<i64>,
    /// Whether Link-Local Multicast Name Resolution (LLMNR) is enabled for the connection. LLMNR is a
    /// protocol based on the Domain Name System (DNS) packet format that allows both IPv4 and IPv6
    /// hosts to perform name resolution for hosts on the same local link. The permitted values are:
    /// "yes" (2) register hostname and resolving for the connection, "no" (0) disable LLMNR for the
    /// interface, "resolve" (1) do not register hostname but allow resolving of LLMNR host names If
    /// unspecified, "default" ultimately depends on the DNS plugin (which for systemd-resolved
    /// currently means "yes"). This feature requires a plugin which supports LLMNR. Otherwise, the
    /// setting has no effect. One such plugin is dns-systemd-resolved.
    pub llmnr: Option<i64>,
    /// Interface name of the controller device or UUID of the controller connection. Deprecated 1.46.
    /// Use "controller" instead, this is just an alias. Deprecated by NetworkManager.
    pub master: Option<String>,
    /// Whether mDNS is enabled for the connection. The permitted values are: "yes" (2) register
    /// hostname and resolving for the connection, "no" (0) disable mDNS for the interface, "resolve"
    /// (1) do not register hostname but allow resolving of mDNS host names and "default" (-1) to allow
    /// lookup of a global default in NetworkManager.conf. If unspecified, "default" ultimately depends
    /// on the DNS plugin. This feature requires a plugin which supports mDNS. Otherwise, the setting
    /// has no effect. Currently the only supported DNS plugin is systemd-resolved. For systemd-
    /// resolved, the default is configurable via MulticastDNS= setting in resolved.conf.
    pub mdns: Option<i64>,
    /// Whether the connection is metered. When updating this property on a currently activated
    /// connection, the change takes effect immediately.
    pub metered: Option<i64>,
    #[serde(rename = "mptcp-flags")]
    pub mptcp_flags: Option<i64>,
    #[serde(rename = "mud-url")]
    pub mud_url: Option<String>,
    #[serde(rename = "multi-connect")]
    pub multi_connect: Option<i64>,
    /// An array of strings defining what access a given user has to this connection.  If this is NULL
    /// or empty, all users are allowed to access this connection; otherwise users are allowed if and
    /// only if they are in this list.  When this is not empty, the connection can be active only when
    /// one of the specified users is logged into an active session.  Each entry is of the form
    /// "[type]:[id]:[reserved]"; for example, "user:dcbw:blah". At this time only the "user" [type] is
    /// allowed.  Any other values are ignored and reserved for future use.  [id] is the username that
    /// this permission refers to, which may not contain the ":" character. Any [reserved] information
    /// present must be ignored and is reserved for future use.  All of [type], [id], and [reserved]
    /// must be valid UTF-8.
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub permissions: Option<Vec<String>>,
    #[serde(rename = "port-type")]
    pub port_type: Option<String>,
    /// Deprecated by NetworkManager.
    #[serde(rename = "read-only")]
    pub read_only: Option<bool>,
    /// List of connection UUIDs that should be activated when the base connection itself is activated.
    /// Currently, only VPN connections are supported.
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub secondaries: Option<Vec<String>>,
    /// Deprecated by NetworkManager.
    #[serde(rename = "slave-type")]
    pub slave_type: Option<String>,
    #[serde(rename = "stable-id")]
    pub stable_id: Option<String>,
    /// The time, in seconds since the Unix Epoch, that the connection was last _successfully_ fully
    /// activated. NetworkManager updates the connection timestamp periodically when the connection is
    /// active to ensure that an active connection has the latest timestamp. The property is only meant
    /// for reading (changes to this property will not be preserved).
    pub timestamp: Option<i64>,
    /// Base type of the connection. For hardware-dependent connections, should contain the setting name
    /// of the hardware-type specific setting (ie, "802-3-ethernet" or "802-11-wireless" or "bluetooth",
    /// etc), and for non-hardware dependent connections like VPN or otherwise, should contain the
    /// setting name of that setting type (ie, "vpn" or "bridge", etc).
    #[serde(rename = "type")]
    pub connection_type: Option<String>,
    /// The connection.uuid is the real identifier of a profile. It cannot change and it must be unique.
    /// It is therefore often best to refer to a profile by UUID, for example with `nmcli connection up
    /// uuid $UUID`. The UUID cannot be changed, except in offline mode. In that case, the special
    /// values "new", "generate" and "" are allowed to generate a new random UUID.
    pub uuid: Option<String>,
    #[serde(rename = "wait-activation-delay")]
    pub wait_activation_delay: Option<i64>,
    #[serde(rename = "wait-device-timeout")]
    pub wait_device_timeout: Option<i64>,
    /// The trust level of a the connection.  Free form case-insensitive string (for example "Home",
    /// "Work", "Public").  NULL or unspecified zone means the connection will be placed in the default
    /// zone as defined by the firewall. When updating this property on a currently activated
    /// connection, the change takes effect immediately.
    pub zone: Option<String>,
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "api-docs", derive(utoipa::ToSchema))]
pub struct ConnectionSettings8021x {
    #[serde(rename = "altsubject-matches")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub altsubject_matches: Option<Vec<String>>,
    #[serde(rename = "anonymous-identity")]
    pub anonymous_identity: Option<String>,
    #[serde(rename = "auth-timeout")]
    pub auth_timeout: Option<i64>,
    #[serde(rename = "ca-cert")]
    pub ca_cert: Option<String>,
    /// Secret value.
    #[serde(rename = "ca-cert-password")]
    pub ca_cert_password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "ca-cert-password-flags")]
    pub ca_cert_password_flags: Option<i64>,
    #[serde(rename = "ca-path")]
    pub ca_path: Option<String>,
    #[serde(rename = "client-cert")]
    pub client_cert: Option<String>,
    /// Secret value.
    #[serde(rename = "client-cert-password")]
    pub client_cert_password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "client-cert-password-flags")]
    pub client_cert_password_flags: Option<i64>,
    #[serde(rename = "domain-match")]
    pub domain_match: Option<String>,
    #[serde(rename = "domain-suffix-match")]
    pub domain_suffix_match: Option<String>,
    /// The allowed EAP method to be used when authenticating to the network with 802.1x.  Valid methods
    /// are: "leap", "md5", "tls", "peap", "ttls", "pwd", and "fast".  Each method requires different
    /// configuration using the properties of this setting; refer to wpa_supplicant documentation for
    /// the allowed combinations.
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub eap: Option<Vec<String>>,
    /// Identity string for EAP authentication methods.  Often the user's user or login name.
    pub identity: Option<String>,
    #[serde(rename = "openssl-ciphers")]
    pub openssl_ciphers: Option<String>,
    /// Whether the 802.1X authentication is optional. If TRUE, the activation will continue even after
    /// a timeout or an authentication failure. Setting the property to TRUE is currently allowed only
    /// for Ethernet connections. If set to FALSE, the activation can continue only after a successful
    /// authentication.
    #[serde(rename = "optional")]
    pub is_optional: Option<bool>,
    #[serde(rename = "pac-file")]
    pub pac_file: Option<String>,
    /// Secret value.
    #[serde(rename = "pac-file-password")]
    pub pac_file_password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "pac-file-password-flags")]
    pub pac_file_password_flags: Option<i64>,
    /// UTF-8 encoded password used for EAP authentication methods. If both the "password" property and
    /// the "password-raw" property are specified, "password" is preferred. Secret value.
    pub password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "password-flags")]
    pub password_flags: Option<i64>,
    /// Secret value.
    #[serde(rename = "password-raw")]
    pub password_raw: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "password-raw-flags")]
    pub password_raw_flags: Option<i64>,
    #[serde(rename = "phase1-auth-flags")]
    pub phase1_auth_flags: Option<i64>,
    #[serde(rename = "phase1-fast-provisioning")]
    pub phase1_fast_provisioning: Option<String>,
    #[serde(rename = "phase1-peaplabel")]
    pub phase1_peaplabel: Option<String>,
    #[serde(rename = "phase1-peapver")]
    pub phase1_peapver: Option<String>,
    #[serde(rename = "phase2-altsubject-matches")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub phase2_altsubject_matches: Option<Vec<String>>,
    #[serde(rename = "phase2-auth")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub phase2_auth: Option<Vec<String>>,
    #[serde(rename = "phase2-autheap")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub phase2_autheap: Option<Vec<String>>,
    #[serde(rename = "phase2-ca-cert")]
    pub phase2_ca_cert: Option<String>,
    /// Secret value.
    #[serde(rename = "phase2-ca-cert-password")]
    pub phase2_ca_cert_password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "phase2-ca-cert-password-flags")]
    pub phase2_ca_cert_password_flags: Option<i64>,
    #[serde(rename = "phase2-ca-path")]
    pub phase2_ca_path: Option<String>,
    #[serde(rename = "phase2-client-cert")]
    pub phase2_client_cert: Option<String>,
    /// Secret value.
    #[serde(rename = "phase2-client-cert-password")]
    pub phase2_client_cert_password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "phase2-client-cert-password-flags")]
    pub phase2_client_cert_password_flags: Option<i64>,
    #[serde(rename = "phase2-domain-match")]
    pub phase2_domain_match: Option<String>,
    #[serde(rename = "phase2-domain-suffix-match")]
    pub phase2_domain_suffix_match: Option<String>,
    #[serde(rename = "phase2-private-key")]
    pub phase2_private_key: Option<String>,
    /// Secret value.
    #[serde(rename = "phase2-private-key-password")]
    pub phase2_private_key_password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "phase2-private-key-password-flags")]
    pub phase2_private_key_password_flags: Option<i64>,
    /// Deprecated by NetworkManager.
    #[serde(rename = "phase2-subject-match")]
    pub phase2_subject_match: Option<String>,
    /// PIN used for EAP authentication methods. Secret value.
    pub pin: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "pin-flags")]
    pub pin_flags: Option<i64>,
    #[serde(rename = "private-key")]
    pub private_key: Option<String>,
    /// Secret value.
    #[serde(rename = "private-key-password")]
    pub private_key_password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "private-key-password-flags")]
    pub private_key_password_flags: Option<i64>,
    /// Deprecated by NetworkManager.
    #[serde(rename = "subject-match")]
    pub subject_match: Option<String>,
    #[serde(rename = "system-ca-certs")]
    pub system_ca_certs: Option<bool>,
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "api-docs", derive(utoipa::ToSchema))]
pub struct ConnectionSettingsGsm {
    /// Deprecated on D-Bus.
    #[serde(rename = "allowed-bands")]
    pub allowed_bands: Option<i64>,
    /// The GPRS Access Point Name specifying the APN used when establishing a data session with the
    /// GSM-based network.  The APN often determines how the user will be billed for their network usage
    /// and whether the user has access to the Internet or just a provider-specific walled-garden, so it
    /// is important to use the correct APN for the user's mobile broadband plan. The APN may only be
    /// composed of the characters a-z, 0-9, ., and - per GSM 03.60 Section 14.9. If the APN is unset
    /// (the default) then it may be detected based on "auto-config" setting. The property can be
    /// explicitly set to the empty string to prevent that and use no APN.
    pub apn: Option<String>,
    #[serde(rename = "auto-config")]
    pub auto_config: Option<bool>,
    #[serde(rename = "device-id")]
    pub device_id: Option<String>,
    #[serde(rename = "device-uid")]
    pub device_uid: Option<String>,
    #[serde(rename = "home-only")]
    pub home_only: Option<bool>,
    #[serde(rename = "initial-eps-bearer-apn")]
    pub initial_eps_bearer_apn: Option<String>,
    #[serde(rename = "initial-eps-bearer-configure")]
    pub initial_eps_bearer_configure: Option<bool>,
    #[serde(rename = "initial-eps-bearer-noauth")]
    pub initial_eps_bearer_noauth: Option<bool>,
    /// Secret value.
    #[serde(rename = "initial-eps-bearer-password")]
    pub initial_eps_bearer_password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "initial-eps-bearer-password-flags")]
    pub initial_eps_bearer_password_flags: Option<i64>,
    #[serde(rename = "initial-eps-bearer-refuse-chap")]
    pub initial_eps_bearer_refuse_chap: Option<bool>,
    #[serde(rename = "initial-eps-bearer-refuse-eap")]
    pub initial_eps_bearer_refuse_eap: Option<bool>,
    #[serde(rename = "initial-eps-bearer-refuse-mschap")]
    pub initial_eps_bearer_refuse_mschap: Option<bool>,
    #[serde(rename = "initial-eps-bearer-refuse-mschapv2")]
    pub initial_eps_bearer_refuse_mschapv2: Option<bool>,
    #[serde(rename = "initial-eps-bearer-refuse-pap")]
    pub initial_eps_bearer_refuse_pap: Option<bool>,
    #[serde(rename = "initial-eps-bearer-username")]
    pub initial_eps_bearer_username: Option<String>,
    /// If non-zero, only transmit packets of the specified size or smaller, breaking larger packets up
    /// into multiple frames.
    pub mtu: Option<i64>,
    #[serde(rename = "network-id")]
    pub network_id: Option<String>,
    /// Deprecated on D-Bus.
    #[serde(rename = "network-type")]
    pub network_type: Option<i64>,
    /// Legacy setting that used to help establishing PPP data sessions for GSM-based modems. Deprecated
    /// by NetworkManager.
    pub number: Option<String>,
    /// The password used to authenticate with the network, if required.  Many providers do not require
    /// a password, or accept any password.  But if a password is required, it is specified here. Secret
    /// value.
    pub password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "password-flags")]
    pub password_flags: Option<i64>,
    /// If the SIM is locked with a PIN it must be unlocked before any other operations are requested.
    /// Specify the PIN here to allow operation of the device. Secret value.
    pub pin: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "pin-flags")]
    pub pin_flags: Option<i64>,
    #[serde(rename = "sim-id")]
    pub sim_id: Option<String>,
    #[serde(rename = "sim-operator-id")]
    pub sim_operator_id: Option<String>,
    /// The username used to authenticate with the network, if required.  Many providers do not require
    /// a username, or accept any username.  But if a username is required, it is specified here.
    pub username: Option<String>,
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "api-docs", derive(utoipa::ToSchema))]
pub struct ConnectionSettingsIp4Config {
    #[serde(rename = "address-data")]
    pub address_data: Option<Vec<BTreeMap<String, Value>>>,
    /// Deprecated on D-Bus.
    #[serde(rename = "address-labels")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub address_labels: Option<Vec<String>>,
    /// Deprecated on D-Bus.
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub addresses: Option<Vec<String>>,
    #[serde(rename = "auto-route-ext-gw")]
    pub auto_route_ext_gw: Option<i64>,
    #[serde(rename = "dad-timeout")]
    pub dad_timeout: Option<i64>,
    #[serde(rename = "dhcp-client-id")]
    pub dhcp_client_id: Option<String>,
    #[serde(rename = "dhcp-dscp")]
    pub dhcp_dscp: Option<String>,
    #[serde(rename = "dhcp-fqdn")]
    pub dhcp_fqdn: Option<String>,
    #[serde(rename = "dhcp-hostname")]
    pub dhcp_hostname: Option<String>,
    #[serde(rename = "dhcp-hostname-flags")]
    pub dhcp_hostname_flags: Option<i64>,
    #[serde(rename = "dhcp-iaid")]
    pub dhcp_iaid: Option<String>,
    #[serde(rename = "dhcp-ipv6-only-preferred")]
    pub dhcp_ipv6_only_preferred: Option<i64>,
    #[serde(rename = "dhcp-reject-servers")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub dhcp_reject_servers: Option<Vec<String>>,
    #[serde(rename = "dhcp-send-hostname")]
    pub dhcp_send_hostname: Option<bool>,
    #[serde(rename = "dhcp-send-hostname-v2")]
    pub dhcp_send_hostname_v2: Option<i64>,
    #[serde(rename = "dhcp-send-release")]
    pub dhcp_send_release: Option<i64>,
    #[serde(rename = "dhcp-timeout")]
    pub dhcp_timeout: Option<i64>,
    #[serde(rename = "dhcp-vendor-class-identifier")]
    pub dhcp_vendor_class_identifier: Option<String>,
    /// Deprecated on D-Bus.
    pub dns: Option<Vec<i64>>,
    #[serde(rename = "dns-data")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub dns_data: Option<Vec<String>>,
    #[serde(rename = "dns-options")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub dns_options: Option<Vec<String>>,
    #[serde(rename = "dns-priority")]
    pub dns_priority: Option<i64>,
    #[serde(rename = "dns-search")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub dns_search: Option<Vec<String>>,
    pub forwarding: Option<i64>,
    pub gateway: Option<String>,
    #[serde(rename = "ignore-auto-dns")]
    pub ignore_auto_dns: Option<bool>,
    #[serde(rename = "ignore-auto-routes")]
    pub ignore_auto_routes: Option<bool>,
    #[serde(rename = "link-local")]
    pub link_local: Option<i64>,
    #[serde(rename = "may-fail")]
    pub may_fail: Option<bool>,
    pub method: Option<String>,
    #[serde(rename = "never-default")]
    pub never_default: Option<bool>,
    #[serde(rename = "replace-local-rule")]
    pub replace_local_rule: Option<i64>,
    #[serde(rename = "required-timeout")]
    pub required_timeout: Option<i64>,
    #[serde(rename = "route-data")]
    pub route_data: Option<Vec<BTreeMap<String, Value>>>,
    #[serde(rename = "route-metric")]
    pub route_metric: Option<i64>,
    #[serde(rename = "route-table")]
    pub route_table: Option<i64>,
    #[serde(rename = "routed-dns")]
    pub routed_dns: Option<i64>,
    /// Deprecated on D-Bus.
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub routes: Option<Vec<String>>,
    #[serde(rename = "routing-rules")]
    pub routing_rules: Option<Vec<BTreeMap<String, Value>>>,
    #[serde(rename = "shared-dhcp-lease-time")]
    pub shared_dhcp_lease_time: Option<i64>,
    #[serde(rename = "shared-dhcp-range")]
    pub shared_dhcp_range: Option<String>,
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "api-docs", derive(utoipa::ToSchema))]
pub struct ConnectionSettingsIp6Config {
    #[serde(rename = "addr-gen-mode")]
    pub addr_gen_mode: Option<i64>,
    #[serde(rename = "address-data")]
    pub address_data: Option<Vec<BTreeMap<String, Value>>>,
    /// Deprecated on D-Bus.
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub addresses: Option<Vec<String>>,
    #[serde(rename = "auto-route-ext-gw")]
    pub auto_route_ext_gw: Option<i64>,
    #[serde(rename = "dad-timeout")]
    pub dad_timeout: Option<i64>,
    #[serde(rename = "dhcp-dscp")]
    pub dhcp_dscp: Option<String>,
    #[serde(rename = "dhcp-duid")]
    pub dhcp_duid: Option<String>,
    #[serde(rename = "dhcp-hostname")]
    pub dhcp_hostname: Option<String>,
    #[serde(rename = "dhcp-hostname-flags")]
    pub dhcp_hostname_flags: Option<i64>,
    #[serde(rename = "dhcp-iaid")]
    pub dhcp_iaid: Option<String>,
    #[serde(rename = "dhcp-pd-hint")]
    pub dhcp_pd_hint: Option<String>,
    #[serde(rename = "dhcp-reject-servers")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub dhcp_reject_servers: Option<Vec<String>>,
    #[serde(rename = "dhcp-send-hostname")]
    pub dhcp_send_hostname: Option<bool>,
    #[serde(rename = "dhcp-send-hostname-v2")]
    pub dhcp_send_hostname_v2: Option<i64>,
    #[serde(rename = "dhcp-send-release")]
    pub dhcp_send_release: Option<i64>,
    #[serde(rename = "dhcp-timeout")]
    pub dhcp_timeout: Option<i64>,
    /// Deprecated on D-Bus.
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub dns: Option<Vec<String>>,
    #[serde(rename = "dns-data")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub dns_data: Option<Vec<String>>,
    #[serde(rename = "dns-options")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub dns_options: Option<Vec<String>>,
    #[serde(rename = "dns-priority")]
    pub dns_priority: Option<i64>,
    #[serde(rename = "dns-search")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub dns_search: Option<Vec<String>>,
    pub forwarding: Option<i64>,
    pub gateway: Option<String>,
    #[serde(rename = "ignore-auto-dns")]
    pub ignore_auto_dns: Option<bool>,
    #[serde(rename = "ignore-auto-routes")]
    pub ignore_auto_routes: Option<bool>,
    #[serde(rename = "ip6-privacy")]
    pub ip6_privacy: Option<i64>,
    #[serde(rename = "may-fail")]
    pub may_fail: Option<bool>,
    pub method: Option<String>,
    pub mtu: Option<i64>,
    #[serde(rename = "never-default")]
    pub never_default: Option<bool>,
    #[serde(rename = "ra-timeout")]
    pub ra_timeout: Option<i64>,
    #[serde(rename = "replace-local-rule")]
    pub replace_local_rule: Option<i64>,
    #[serde(rename = "required-timeout")]
    pub required_timeout: Option<i64>,
    #[serde(rename = "route-data")]
    pub route_data: Option<Vec<BTreeMap<String, Value>>>,
    #[serde(rename = "route-metric")]
    pub route_metric: Option<i64>,
    #[serde(rename = "route-table")]
    pub route_table: Option<i64>,
    #[serde(rename = "routed-dns")]
    pub routed_dns: Option<i64>,
    /// Deprecated on D-Bus.
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub routes: Option<Vec<String>>,
    #[serde(rename = "routing-rules")]
    pub routing_rules: Option<Vec<BTreeMap<String, Value>>>,
    #[serde(rename = "shared-dhcp-lease-time")]
    pub shared_dhcp_lease_time: Option<i64>,
    #[serde(rename = "shared-dhcp-range")]
    pub shared_dhcp_range: Option<String>,
    #[serde(rename = "temp-preferred-lifetime")]
    pub temp_preferred_lifetime: Option<i64>,
    #[serde(rename = "temp-valid-lifetime")]
    pub temp_valid_lifetime: Option<i64>,
    pub token: Option<String>,
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "api-docs", derive(utoipa::ToSchema))]
pub struct ConnectionSettingsWired {
    #[serde(rename = "accept-all-mac-addresses")]
    pub accept_all_mac_addresses: Option<i64>,
    #[serde(rename = "assigned-mac-address")]
    pub assigned_mac_address: Option<String>,
    #[serde(rename = "auto-negotiate")]
    pub auto_negotiate: Option<bool>,
    /// Deprecated on D-Bus.
    #[serde(rename = "cloned-mac-address")]
    pub cloned_mac_address: Option<String>,
    pub duplex: Option<String>,
    #[serde(rename = "generate-mac-address-mask")]
    pub generate_mac_address_mask: Option<String>,
    #[serde(rename = "mac-address")]
    pub mac_address: Option<String>,
    /// Deprecated by NetworkManager.
    #[serde(rename = "mac-address-blacklist")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub mac_address_blacklist: Option<Vec<String>>,
    #[serde(rename = "mac-address-denylist")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub mac_address_denylist: Option<Vec<String>>,
    pub mtu: Option<i64>,
    pub port: Option<String>,
    #[serde(rename = "s390-nettype")]
    pub s390_nettype: Option<String>,
    #[serde(rename = "s390-options")]
    pub s390_options: Option<BTreeMap<String, String>>,
    #[serde(rename = "s390-subchannels")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub s390_subchannels: Option<Vec<String>>,
    pub speed: Option<i64>,
    #[serde(rename = "wake-on-lan")]
    pub wake_on_lan: Option<i64>,
    #[serde(rename = "wake-on-lan-password")]
    pub wake_on_lan_password: Option<String>,
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "api-docs", derive(utoipa::ToSchema))]
pub struct ConnectionSettingsWireless {
    pub acs: Option<i64>,
    #[serde(rename = "ap-config-file")]
    pub ap_config_file: Option<String>,
    #[serde(rename = "ap-isolation")]
    pub ap_isolation: Option<i64>,
    #[serde(rename = "assigned-mac-address")]
    pub assigned_mac_address: Option<String>,
    #[serde(rename = "auth-timeout")]
    pub auth_timeout: Option<i64>,
    pub band: Option<String>,
    pub bgscan: Option<String>,
    pub bssid: Option<String>,
    pub ccx: Option<i64>,
    pub channel: Option<i64>,
    #[serde(rename = "channel-width")]
    pub channel_width: Option<i64>,
    #[serde(rename = "client-name")]
    pub client_name: Option<String>,
    /// Deprecated on D-Bus.
    #[serde(rename = "cloned-mac-address")]
    pub cloned_mac_address: Option<String>,
    pub dms: Option<i64>,
    #[serde(rename = "frequency-dfs")]
    pub frequency_dfs: Option<i64>,
    #[serde(rename = "frequency-list")]
    pub frequency_list: Option<String>,
    #[serde(rename = "generate-mac-address-mask")]
    pub generate_mac_address_mask: Option<String>,
    pub hidden: Option<bool>,
    #[serde(rename = "mac-address")]
    pub mac_address: Option<String>,
    /// Deprecated by NetworkManager.
    #[serde(rename = "mac-address-blacklist")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub mac_address_blacklist: Option<Vec<String>>,
    #[serde(rename = "mac-address-denylist")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub mac_address_denylist: Option<Vec<String>>,
    /// Deprecated by NetworkManager.
    #[serde(rename = "mac-address-randomization")]
    pub mac_address_randomization: Option<i64>,
    #[serde(rename = "max-scan-interval")]
    pub max_scan_interval: Option<i64>,
    pub mode: Option<String>,
    pub mtu: Option<i64>,
    pub powersave: Option<i64>,
    /// Deprecated by NetworkManager.
    pub rate: Option<i64>,
    #[serde(rename = "scan-delay")]
    pub scan_delay: Option<i64>,
    #[serde(rename = "scan-dwell")]
    pub scan_dwell: Option<i64>,
    #[serde(rename = "scan-passive-dwell")]
    pub scan_passive_dwell: Option<i64>,
    #[serde(rename = "scan-roam-delta")]
    pub scan_roam_delta: Option<i64>,
    #[serde(rename = "scan-suspend-time")]
    pub scan_suspend_time: Option<i64>,
    /// Deprecated on D-Bus.
    pub security: Option<String>,
    #[serde(rename = "seen-bssids")]
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub seen_bssids: Option<Vec<String>>,
    pub ssid: String,
    #[serde(rename = "summit-flags")]
    pub summit_flags: Option<i64>,
    /// Deprecated by NetworkManager.
    #[serde(rename = "tx-power")]
    pub tx_power: Option<i64>,
    #[serde(rename = "wake-on-wlan")]
    pub wake_on_wlan: Option<i64>,
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "api-docs", derive(utoipa::ToSchema))]
pub struct ConnectionSettingsWirelessSecurity {
    #[serde(rename = "auth-alg")]
    pub auth_alg: Option<String>,
    pub fils: Option<i64>,
    pub ft: Option<i64>,
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub group: Option<Vec<String>>,
    #[serde(rename = "key-mgmt")]
    pub key_mgmt: String,
    /// Secret value.
    #[serde(rename = "leap-password")]
    pub leap_password: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "leap-password-flags")]
    pub leap_password_flags: Option<i64>,
    #[serde(rename = "leap-username")]
    pub leap_username: Option<String>,
    #[serde(rename = "owe-only")]
    pub owe_only: Option<i64>,
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub pairwise: Option<Vec<String>>,
    pub pmf: Option<i64>,
    #[serde(rename = "proactive-key-caching")]
    pub proactive_key_caching: Option<String>,
    #[serde(default, deserialize_with = "deserialize_optional_string_vec")]
    pub proto: Option<Vec<String>>,
    /// Secret value.
    pub psk: Option<String>,
    /// Secret-flags field.
    #[serde(rename = "psk-flags")]
    pub psk_flags: Option<i64>,
    /// Secret-flags field.
    #[serde(rename = "wep-key-flags")]
    pub wep_key_flags: Option<i64>,
    #[serde(rename = "wep-key-type")]
    pub wep_key_type: Option<i64>,
    /// Secret value.
    #[serde(rename = "wep-key0")]
    pub wep_key0: Option<String>,
    /// Secret value.
    #[serde(rename = "wep-key1")]
    pub wep_key1: Option<String>,
    /// Secret value.
    #[serde(rename = "wep-key2")]
    pub wep_key2: Option<String>,
    /// Secret value.
    #[serde(rename = "wep-key3")]
    pub wep_key3: Option<String>,
    #[serde(rename = "wep-tx-keyidx")]
    pub wep_tx_keyidx: Option<i64>,
    #[serde(rename = "wps-method")]
    pub wps_method: Option<i64>,
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "api-docs", derive(utoipa::ToSchema))]
pub struct ConnectionSettingsWifiP2p {
    #[serde(rename = "device-name")]
    pub device_name: Option<String>,
    /// Frequency (MHz).
    pub frequency: Option<i64>,
    /// The P2P device that should be connected to. Currently, this is the only way to create or join a
    /// group.
    pub peer: Option<String>,
    #[serde(rename = "peer-device-name")]
    pub peer_device_name: Option<String>,
    #[serde(rename = "wfd-ies")]
    pub wfd_ies: Option<String>,
    #[serde(rename = "wps-method")]
    pub wps_method: Option<i64>,
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "api-docs", derive(utoipa::ToSchema))]
pub struct ConnectionProfile {
    #[serde(rename = "802-1x")]
    pub enterprise_auth: Option<ConnectionSettings8021x>,
    pub connection: ConnectionSettingsConnection,
    pub gsm: Option<ConnectionSettingsGsm>,
    pub ipv4: Option<ConnectionSettingsIp4Config>,
    pub ipv6: Option<ConnectionSettingsIp6Config>,
    #[serde(rename = "802-3-ethernet")]
    pub wired: Option<ConnectionSettingsWired>,
    #[serde(rename = "802-11-wireless")]
    pub wireless: Option<ConnectionSettingsWireless>,
    #[serde(rename = "802-11-wireless-security")]
    pub wireless_security: Option<ConnectionSettingsWirelessSecurity>,
    #[serde(rename = "wifi-p2p")]
    pub wifi_p2p: Option<ConnectionSettingsWifiP2p>,
    pub activated: Option<bool>,
}
