//
// SPDX-License-Identifier: LicenseRef-Ezurio-Clause
// Copyright (C) 2026 Ezurio LLC.
//

use env_filter::{Builder as FilterBuilder, FilteredLog};
use log::info;
use summit_rcm_core::config;
use summit_rcm_core::definition::CURRENT_PROCESS_LOG_IDENTIFIER;
use systemd_journal_logger::JournalLog;

#[cfg(feature = "at-interface")]
pub use summit_rcm_at as at_interface;
pub use summit_rcm_core as core;
#[cfg(any(feature = "api-v2", feature = "api-legacy"))]
pub use summit_rcm_web as web;
#[cfg(feature = "api-docs")]
pub use summit_rcm_web::openapi;

// Keep every enabled plugin crate linked so its inventory registrations
// survive. The list is generated by build.rs from the manifest dependencies.
include!(concat!(env!("OUT_DIR"), "/plugin_links.rs"));

pub fn build_log_filter() -> env_filter::Filter {
    let mut builder = FilterBuilder::new();
    builder
        .filter_level(log::LevelFilter::Warn)
        .filter_module("summit_rcm", log::LevelFilter::Info);
    builder.build()
}

/// Install Summit RCM's default journal logger.
///
/// Embedding applications may skip this and install their own logger/tracing
/// pipeline before calling [`run`] or [`run_services`].
pub fn init_logger() {
    let filter = build_log_filter();
    let max_level = filter.filter();

    if let Ok(logger) = JournalLog::new() {
        let logger = logger
            .with_syslog_identifier(CURRENT_PROCESS_LOG_IDENTIFIER.to_string())
            .with_extra_fields([("VERSION", env!("CARGO_PKG_VERSION"))]);
        log::set_boxed_logger(Box::new(FilteredLog::new(logger, filter)))
            .expect("logger initialization should succeed");
        log::set_max_level(max_level);
    }
}

#[cfg(any(feature = "at-interface", feature = "api-v2", feature = "api-legacy"))]
mod runtime {
    use futures_util::future::try_join_all;
    #[cfg(feature = "at-interface")]
    use summit_rcm_at as at_interface;
    #[cfg(any(feature = "api-v2", feature = "api-legacy"))]
    use summit_rcm_web as web;
    #[cfg(unix)]
    use tokio::signal::unix::{SignalKind, signal};
    use tokio::task::{JoinHandle, LocalSet};

    async fn wait_for_task(
        name: &'static str,
        handle: JoinHandle<anyhow::Result<()>>,
    ) -> anyhow::Result<()> {
        handle
            .await
            .map_err(|error| anyhow::anyhow!("{name} task failed to join: {error}"))?
            .map_err(|error| anyhow::anyhow!("{name} task failed: {error}"))
    }

    async fn shutdown_signal() {
        #[cfg(unix)]
        {
            let mut sigterm =
                signal(SignalKind::terminate()).expect("SIGTERM handler should be installed");
            tokio::select! {
                _ = tokio::signal::ctrl_c() => {}
                _ = sigterm.recv() => {}
            }
        }

        #[cfg(not(unix))]
        {
            let _ = tokio::signal::ctrl_c().await;
        }
    }

    #[allow(clippy::vec_init_then_push)]
    pub async fn run() -> anyhow::Result<()> {
        let local = LocalSet::new();
        local
            .run_until(async move {
                for startup in summit_rcm_core::startup_hooks() {
                    startup();
                }

                let (shutdown_tx, shutdown_rx) = tokio::sync::watch::channel(false);
                let mut tasks: Vec<(&'static str, JoinHandle<anyhow::Result<()>>)> = Vec::new();

                #[cfg(feature = "at-interface")]
                tasks.push((
                    "AT interface",
                    at_interface::spawn_task(shutdown_rx.clone()),
                ));

                #[cfg(any(feature = "api-v2", feature = "api-legacy"))]
                tasks.push(("web", web::spawn_task(shutdown_rx)));

                let tasks_future = try_join_all(
                    tasks
                        .into_iter()
                        .map(|(name, handle)| wait_for_task(name, handle)),
                );
                tokio::pin!(tasks_future);

                tokio::select! {
                    result = &mut tasks_future => {
                        result?;
                    }
                    _ = shutdown_signal() => {
                        log::info!("Shutdown signal received");
                        summit_rcm_core::utils::signal_shutdown();
                        let _ = shutdown_tx.send(true);
                        tasks_future.await?;
                    }
                }

                Ok::<(), anyhow::Error>(())
            })
            .await
    }
}

#[cfg(not(any(feature = "at-interface", feature = "api-v2", feature = "api-legacy")))]
mod runtime {
    pub async fn run() -> anyhow::Result<()> {
        log::warn!(
            "No features enabled — nothing to do. Enable 'api-v2', 'api-legacy', and/or 'at-interface'."
        );
        Ok(())
    }
}

/// Run Summit RCM's interface tasks after the embedding application has done
/// any process setup it wants (logger, tracing, extra startup, etc.).
pub async fn run_services() -> anyhow::Result<()> {
    config::SystemSettingsManage::ensure_section();
    runtime::run().await
}

/// Run Summit RCM after any desired process setup (logger, tracing, etc.).
pub async fn run() -> anyhow::Result<()> {
    info!(
        "Summit RCM starting (version {})",
        env!("CARGO_PKG_VERSION")
    );

    run_services().await?;

    info!("Summit RCM stopped");
    Ok(())
}
